# Generated by Django 3.0.1 on 2020-07-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ad', verbose_name='image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimage', to='ads.Ad')),
            ],
        ),
    ]
