# Generated by Django 3.0.1 on 2020-07-24 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 52, 31, 579696, tzinfo=utc)),
        ),
    ]
